### ISSUE TITLE
Menu does not appear

### ISSUE THREAD

**Issue by neurogen-dev** [Mekap/lemekap_menujobs#1]
The menu and the text with the help does not appear. The job is assigned correctly.

**Comment by Mekap** [comment]
Make sure that you are on the proper coordinates. The radius may be increased as you need.
In the example given in the config. file, the point is behind Valentine's bar,
 not inside. Make sure you also have the vorp_inventory dependency installed on your server.
 And, make sure that they are no syntaxe mistakes on your .lua file, this is usually the issue most people have.
I've tested the 1.0 version on my end, and everything works properly. Closing the ticket.
